### ISSUE TITLE
About se,cv  and bgm

### ISSUE THREAD

**Issue by Summer1218** [avgjs/avg-core#29]
I can't find controling code about se,cv and bgm,.Could you tell me where the file catalogue is?

**Comment by Icemic** [comment]
Hi,

They are at https://github.com/avgjs/avg-core/tree/dev/src/plugins/audio

And the document has been updated, you'll find more details at https://avgjs.github.io/docs/#/plugins-sound now!

**Comment by Summer1218** [comment]
Thanks
