### ISSUE TITLE
node 13.x安装报错

### ISSUE THREAD

**Issue by mhkz** [avgjs/avg-core#34]
node 版本  v12.10.0

Mac 版本 10.15.2

报错信息
npm WARN deprecated ffmpeg-static@2.7.0: ffmpeg-static@2 won't be updated with new ffmpeg binaries anymore. Use ffmpeg-static@latest.
npm ERR! Unexpected end of JSON input while parsing near '...wqMgKK+JgWsAQik5o0HTL'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/guofeng/.npm/_logs/2020-03-02T11_03_28_462Z-debug.log

**Comment by Icemic** [comment]
You've been GFWed, check network.
